[package]
name = "dss-indicator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
appindicator3 = "0.3.0"
glib = "0.18.0"
gtk = "0.18.1"
open = "5.0.1"
