#!/bin/bash
# get list of all Deployments that are not ready yet
ret=`microk8s.kubectl get deployments -n dss -o jsonpath='{range .items[?(@.status.readyReplicas==1)]}{.metadata.name}{"\n"}{end}' | wc -l`
echo $ret
if [ $ret -lt 2 ];
then
	echo "Not ready"
	exit 1
fi
exit 0
